from agent.state import AgentState
from agent.tools.git import (
    create_branch, commit_changes, push_branch, create_pr
)
from agent.adapters.linear_adapter import LinearAdapter


def publisher_node(state: AgentState) -> dict:
    """Handle git operations and PR creation."""
    issue = state.get("current_issue")
    if not issue:
        return {"messages": state.get("messages", []) + ["No issue to publish"]}

    # Create branch name from issue identifier
    branch_name = f"ai/{issue.identifier.lower()}"

    # Create and checkout branch
    success, branch_msg = create_branch(branch_name)
    if not success:
        return {
            "status": "failed",
            "messages": state.get("messages", []) + [branch_msg]
        }

    # Commit the generated contract
    contract = state.get("current_contract")
    if contract:
        commit_message = f"feat({issue.identifier}): Add data contract\n\nGenerated by AI Factory"
        commit_changes(commit_message)

    # Push and create PR
    push_branch(branch_name)
    success, pr_url = create_pr(
        title=f"[{issue.identifier}] {issue.title}",
        body=f"## Summary\n\n{issue.description or 'AI-generated implementation'}\n\n---\n*Generated by Software Factory*"
    )

    if success:
        # Update Linear issue
        adapter = LinearAdapter()
        adapter.transition_issue(issue.id, "AI: Review")
        adapter.add_comment(issue.id, f"✅ PR created: {pr_url}")

        return {
            "status": "published",
            "pr_url": pr_url,
            "messages": state.get("messages", []) + [f"PR created: {pr_url}"]
        }

    return {
        "status": "failed",
        "messages": state.get("messages", []) + ["Failed to create PR"]
    }
