import os
import json
from agent.state import AgentState
from agent.tools.git import (
    create_branch, commit_changes, push_branch, create_pr
)
from agent.adapters.linear_adapter import LinearAdapter


def publisher_node(state: AgentState) -> dict:
    """Handle git operations and PR creation."""
    issue = state.get("current_issue")
    if not issue:
        return {"messages": state.get("messages", []) + ["No issue to publish"]}

    request_type = state.get("request_type", "general")
    
    # Create branch name from issue identifier
    branch_name = f"ai/{issue.identifier.lower()}"

    # Create and checkout branch
    success, branch_msg = create_branch(branch_name)
    if not success:
        return {
            "status": "failed",
            "messages": state.get("messages", []) + [branch_msg]
        }

    # Handle based on request type
    artifact = state.get("current_contract")
    
    if request_type == "requires_contract" and artifact:
        # Contract request - write to contracts/
        contracts_dir = "contracts"
        os.makedirs(contracts_dir, exist_ok=True)
        
        try:
            artifact_data = json.loads(artifact)
            artifact_name = artifact_data.get("name", issue.identifier).lower()
        except json.JSONDecodeError:
            artifact_name = issue.identifier.lower()
        
        artifact_file = os.path.join(contracts_dir, f"{artifact_name}.json")
        with open(artifact_file, "w") as f:
            f.write(artifact)
        
        commit_message = f"feat({issue.identifier}): Add {artifact_name} data contract\n\nGenerated by AI Factory"
        commit_changes(commit_message, [artifact_file])
        
    elif request_type == "infrastructure" and artifact:
        # Infrastructure request - write to infra/
        try:
            artifact_data = json.loads(artifact)
            artifact_name = artifact_data.get("name", issue.identifier.lower())
            artifact_type = artifact_data.get("type", "config")
            artifact_content = artifact_data.get("content", artifact)
        except json.JSONDecodeError:
            artifact_name = issue.identifier.lower()
            artifact_type = "config"
            artifact_content = artifact

        infra_dir = f"infra/{artifact_name}"
        os.makedirs(infra_dir, exist_ok=True)
        
        extensions = {"dockerfile": "", "ci_config": ".yml", "script": ".sh", "config": ".json"}
        ext = extensions.get(artifact_type, ".txt")
        filename = f"{artifact_name}{ext}" if ext else "Dockerfile"
        
        artifact_file = os.path.join(infra_dir, filename)
        with open(artifact_file, "w") as f:
            f.write(artifact_content)
        
        commit_message = f"chore({issue.identifier}): Add {artifact_name}\n\nGenerated by AI Factory"
        commit_changes(commit_message, [artifact_file])
        
    elif artifact:
        # General request - write to src/
        try:
            artifact_data = json.loads(artifact)
            artifact_name = artifact_data.get("name", issue.identifier.lower())
            language = artifact_data.get("language", "python")
            artifact_content = artifact_data.get("content", artifact)
        except json.JSONDecodeError:
            artifact_name = issue.identifier.lower()
            language = "python"
            artifact_content = artifact

        src_dir = f"src/{artifact_name}"
        os.makedirs(src_dir, exist_ok=True)
        
        lang_extensions = {"python": ".py", "typescript": ".ts", "javascript": ".js"}
        ext = lang_extensions.get(language, ".txt")
        
        artifact_file = os.path.join(src_dir, f"{artifact_name}{ext}")
        with open(artifact_file, "w") as f:
            f.write(artifact_content)
        
        commit_message = f"feat({issue.identifier}): Add {artifact_name}\n\nGenerated by AI Factory"
        commit_changes(commit_message, [artifact_file])
    else:
        return {
            "status": "failed",
            "messages": state.get("messages", []) + ["No artifact generated to commit"]
        }

    # Push and create PR
    push_branch(branch_name)
    success, pr_result = create_pr(
        title=f"[{issue.identifier}] {issue.title}",
        body=f"## Summary\n\n{issue.description or 'AI-generated implementation'}\n\n---\n*Generated by Software Factory*"
    )

    if success:
        adapter = LinearAdapter()
        adapter.transition_issue(issue.id, "AI: Review")
        adapter.add_comment(issue.id, f"✅ PR created: {pr_result}")

        return {
            "status": "published",
            "pr_url": pr_result,
            "stack_base_branch": branch_name,
            "messages": state.get("messages", []) + [f"PR created: {pr_result}"]
        }

    return {
        "status": "failed",
        "messages": state.get("messages", []) + [f"Failed to create PR: {pr_result}"]
    }
