from typing import TypedDict, Literal, List, Optional, Any
from pydantic import BaseModel


class ContractSchema(BaseModel):
    """The data contract being reviewed."""
    name: str
    fields: dict
    description: str


class ReviewFeedback(BaseModel):
    """Feedback from a review agent."""
    agent: str
    approved: bool
    concerns: List[str]
    suggestions: List[str]


class UserStory(BaseModel):
    """A user story with acceptance criteria."""
    as_a: str
    i_want: str
    so_that: str
    acceptance_criteria: List[str]


class PRD(BaseModel):
    """Product Requirements Document generated by PM agent."""
    title: str
    problem_statement: str
    user_stories: List[UserStory]
    edge_cases: List[str]
    out_of_scope: List[str]
    success_metrics: List[str]
    priority: Literal["P0", "P1", "P2"]
    estimated_complexity: Literal["S", "M", "L", "XL"]


class WorkItem(BaseModel):
    """A single work item in the stacked PR workflow."""
    type: Literal["CONTRACT", "BACKEND", "FRONTEND"]
    title: str
    description: str
    acceptance_criteria: List[str] = []
    depends_on: Optional[str] = None
    branch_name: Optional[str] = None
    pr_url: Optional[str] = None
    status: Literal["pending", "in_progress", "completed", "failed"] = "pending"


class AgentState(TypedDict):
    """Shared state across all agents in the graph."""
    task_description: str
    current_contract: Optional[str]
    review_feedback: List[ReviewFeedback]
    iteration_count: int
    status: Literal["drafting", "reviewing", "approved", "failed", "published", "architected", "stack_complete", "working_contract", "working_backend", "working_frontend", "prd_ready", "awaiting_approval", "prd_approved", "implementation_ready", "needs_correction"]
    messages: List[str]
    # PM Agent: PRD workflow
    prd: Optional[Any]
    prd_feedback: Optional[str]
    requires_human_approval: bool
    # Phase 2: Linear integration
    current_issue: Optional[Any]
    pr_url: Optional[str]
    # Request classification
    request_type: Optional[Literal["requires_contract", "infrastructure", "general"]]
    # Phase 3: Stacked PRs
    work_items: Optional[List[Any]]
    current_work_index: Optional[int]
    current_work_item: Optional[Any]
    stack_base_branch: Optional[str]
    # Phase 3: Ephemeral environments
    ephemeral_status: Optional[str]
    preview_url: Optional[str]
    ephemeral_db_url: Optional[str]
    # Phase 3: Testing
    test_status: Optional[str]
    test_output: Optional[str]
    # Phase 3: Telemetry
    telemetry_status: Optional[str]
    error_count: Optional[int]
    action: Optional[str]
    # Phase 3: Revert
    revert_status: Optional[str]
    reverted_commit: Optional[str]
    # Implementation Engineer Agent: Claude Code CLI integration
    implementation_engineer_mode: Optional[Literal["CONTRACT", "BACKEND", "FRONTEND"]]
    claude_code_result: Optional[Any]
    validation_status: Optional[Literal["passed", "failed"]]
    validation_errors: Optional[str]
    correction_count: Optional[int]
    workspace_path: Optional[str]
